# Generated by Django 5.2.3 on 2026-02-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('Team Leader', 'Leader'), ('Member', 'Member')], default='Member', max_length=20),
        ),
    ]
